name: synchrowise
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_auth: ^3.3.6
  firebase: ^9.0.2
  firebase_core: ^1.12.0
  get_it: ^7.2.0
  dartz: ^0.10.1
  equatable: ^2.0.3
  google_sign_in: ^5.2.3
  matrix4_transform: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
